name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: "5.12.10"
          host: "linux"
          target: "desktop"
          arch: "gcc_64"
          dir: "${{github.workspace}}/QtCommunicationClasses/"
          install-deps: "true"

      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen

      - name: Install qmake
        run: |
          sudo apt-get update
          sudo apt-get install -y qt5-qmake

      - name: Build
        run: qmake && make
        working-directory: QtCommunicationClasses

      - name: Doxygen Deploy
        uses: DenverCoder1/doxygen-github-pages-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs/html
