name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: "5.12.10"
          host: "windows"
          target: "desktop"
          arch: "win64_mingw73"
          dir: "${{github.workspace}}/QtCommunicationClasses/"
          install-deps: "true"

      - name: Build
        run: qmake && make
        working-directory: QtCommunicationClasses

  deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: DenverCoder1/doxygen-github-pages-action@v1
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: gh-pages
            folder: docs/html
